default:
    gherkin:
        cache: ~
    autoload:
        '': '%paths.base%/../tests/btd/features/bootstrap'
    suites:
        default:
            paths:
                - '%paths.base%/../tests/btd/features'
            contexts:
                - App\Contexts\NavigationContext:
                    session: '@session'
                    kernel: '@kernel'

    extensions:
        Behat\Symfony2Extension:
            kernel:
                env:   test
                debug: true
                class: App\Kernel
        Behat\MinkExtension:
            sessions:
                default:
                    symfony2: ~