Feature: 12th ICAANE site navigation behaviour

  Scenario Outline: Navigate to URLs
    Given I am not logged in
    When I navigate to "<request_url>"
    Then I got <status> status
    And I land to "<land_url>"

    Examples:
      | request_url   | status | land_url  |
      | /             | 200    | /         |
      | /register     | 200    | /register |
      | /confirmation | 200    | /         |
      | /list         | 200    | /login    |

  Scenario: Fill the register form with valid data
    Given I have the right DB schema
    And I navigate to "/register"
    And I fill form with valid data:
      | id                    | type   | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | speaker_main_author   | text   | R. Smith                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | speaker_other_authors | text   | S. White, B. Mars                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | speaker_title         | text   | Using Behat for Behaviour tests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | speaker_affiliation   | text   | University of Bologna                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | speaker_theme         | select | 1. Field Reports                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | speaker_abstract      | text   | venenatis cras sed felis eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper quis lectus nulla at volutpat diam ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam non nisi est sit amet facilisis magna etiam tempor orci eu lobortis elementum nibh tellus molestie nunc non blandit massa enim nec dui nunc mattis enim ut tellus elementum sagittis vitae et leo duis ut diam quam nulla porttitor massa id |
      | speaker_email         | text   | mail@example.net                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | speaker_payment_id    | text   | SWIFT-35453                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | speaker_remarks       | text   | Registration remarks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
    When I click the "speaker_save" button
    Then I land to "/confirmation"
    And I got the right registration number